### ISSUE TITLE
com.spotify.docker.client.exceptions.DockerException: Permission denied

### ISSUE THREAD

**Issue by JakkoJokiranta** [gocd/docker-registry-artifact-plugin#303]
I am getting this error when building with upstream artifact dependency
It does not occurs always, sometimes it works at re-run, depending how lucky we are at that moment

I used plugin version 1.1.0-104, and tried with latest experimental release 1.1.0-125 by the way. Both still failing

gocd version: 20.2.0
docker-registry version: 2.7.1

```
[cd.go.artifact.docker.registry] Pulling docker image `<my_docker_registry>/<my_image>:stable` from docker registry `<my_docker_registry>`.

[cd.go.artifact.docker.registry] Failed pull docker image: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied
The plugin sent a response that could not be understood by Go. Plugin returned with code '500' and the following response: 'Failed pull docker image: com.spotify.docker.client.exceptions.DockerException: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: java.io.IOException: Permission denied'
```

**Comment by varshavaradarajan** [comment]
@JakkoJokiranta - I guess this is intermittent based on which gocd agent picks up this job to fetch the artifact. Maybe check the permissions on `/var/run/docker.sock` on the gocd agent when the issue occurs?

**Comment by JakkoJokiranta** [comment]
Thats a thing, Im using elastic agents with dind oficial image for all pipelines
Something curious is that this only occurs when pulling from specific pipeline, a PHP Base image builder one.
Once I thought it could be registry's cache or something because of image overriding (pushing as 'stable') because most of times it works, I left some time between update and build with dependency, or I restarted both, gocd and docker-registry

All nodes are equal, managed by Scaleway's Kapsule

Also Docker registry is deployed inside kubernetes, and agents has credentials for it

**Comment by ketan** [comment]
Do you have a full stacktrace? The stack trace you provided does not really
contain information that we could use to get to the root cause.

- Ketan

**Comment by JakkoJokiranta** [comment]
From /go-working-dir/logs/go-server.log, I catch this which is a stack trace of a failing pipeline

It seems that agent deploys missing a cookie, that could explain why it gets Permission Denied

`2020-03-23 09:33:29,512 INFO  [ThreadPoolTaskScheduler-7] ScheduleService:160 - [Pipeline Schedule] Scheduling pipeline <Pipeline> with build cause [ModificationBuildCause: modified by <me> ]
2020-03-23 09:33:29,531 INFO  [ThreadPoolTaskScheduler-7] PipelineRepository:78 - Start updating pipeline timeline
2020-03-23 09:33:29,535 INFO  [ThreadPoolTaskScheduler-7] PipelineRepository:84 - Pipeline timeline updated
2020-03-23 09:33:55,265 INFO  [qtp415774130-22] AgentRegistrationController:266 - [Agent Auto Registration] Auto registering agent with uuid 53e465d7-4c57-4c55-81e8-28a19e0e27d4 
2020-03-23 09:33:55,673 WARN  [qtp415774130-41] AgentService:510 - Agent [Agent [gocd-agent-dind-6df71a7f-9727-4b6d-a2f1-a3e0246ccbd5, 100.64.0.21, 53e465d7-4c57-4c55-81e8-28a19e0e27d4, null]] has no cookie set
2020-03-23 09:33:55,674 ERROR [qtp415774130-41] BuildRepositoryRemoteImpl:56 - Error occurred in com.thoughtworks.go.server.service.ElasticAgentRuntimeInfo@4e7c8e03[elasticAgentId=gocd-agent-dind-6df71a7f-9727-4b6d-a2f1-a3e0246ccbd5,elasticPluginId=cd.go.contrib.elasticagent.kubernetes,identifier=Agent [gocd-agent-dind-6df71a7f-9727-4b6d-a2f1-a3e0246ccbd5, 100.64.0.21, 53e465d7-4c57-4c55-81e8-28a19e0e27d4],runtimeStatus=Idle,buildingInfo=AgentBuildingInfo[, ],location=/go,usableSpace=73111572480,operatingSystemName=Alpine Linux v3.11,cookie=<null>] ping.
com.thoughtworks.go.server.service.AgentNoCookieSetException: Agent [Agent [gocd-agent-dind-6df71a7f-9727-4b6d-a2f1-a3e0246ccbd5, 100.64.0.21, 53e465d7-4c57-4c55-81e8-28a19e0e27d4, null]] has no cookie set
        at com.thoughtworks.go.server.service.AgentService.bombIfAgentDoesNotHaveCookie(AgentService.java:511)
        at com.thoughtworks.go.server.service.AgentService.updateRuntimeInfo(AgentService.java:225)
        at com.thoughtworks.go.remote.BuildRepositoryRemoteImpl.ping(BuildRepositoryRemoteImpl.java:51)
        at com.thoughtworks.go.server.messaging.BuildRepositoryMessageProducer.ping(BuildRepositoryMessageProducer.java:47)
        at jdk.internal.reflect.GeneratedMethodAccessor185.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:333)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
        at org.springframework.remoting.support.RemoteInvocationTraceInterceptor.invoke(RemoteInvocationTraceInterceptor.java:78)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213)
        at com.sun.proxy.$Proxy105.ping(Unknown Source)
        at jdk.internal.reflect.GeneratedMethodAccessor184.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.springframework.remoting.support.RemoteInvocation.invoke(RemoteInvocation.java:212)
        at org.springframework.remoting.support.DefaultRemoteInvocationExecutor.invoke(DefaultRemoteInvocationExecutor.java:39)
        at org.springframework.remoting.support.RemoteInvocationBasedExporter.invoke(RemoteInvocationBasedExporter.java:78)
        at org.springframework.remoting.support.RemoteInvocationBasedExporter.invokeAndCreateResult(RemoteInvocationBasedExporter.java:114)
        at org.springframework.remoting.httpinvoker.HttpInvokerServiceExporter.handleRequest(HttpInvokerServiceExporter.java:80)
        at org.springframework.web.servlet.mvc.HttpRequestHandlerAdapter.handle(HttpRequestHandlerAdapter.java:51)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:901)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
      ...
`

**Comment by JakkoJokiranta** [comment]
I got some more logs..

from wrapper.log
```
INFO   | jvm 1    | 2020/03/23 11:42:53 | 2020-03-23 11:42:53,010 INFO  [qtp415774130-27] BuildRepositoryRemoteImpl:96 - [Agent [gocd-agent-dind-02ae1fc0-c94a-49a7-9831-f9fa2efca25d, 100.64.0.175, dfa856e5-93de-49f2-b40a-1d3b30fcb179, 93d74bcb-2e44-43b2-bb5d-40e16712c7f1]] is reporting result [Failed] for [Build [<project>/73/build/1/build/5669]]
INFO   | jvm 1    | 2020/03/23 11:42:53 | 2020-03-23 11:42:53,037 INFO  [qtp415774130-29] BuildRepositoryRemoteImpl:96 - [Agent [gocd-agent-dind-02ae1fc0-c94a-49a7-9831-f9fa2efca25d, 100.64.0.175, dfa856e5-93de-49f2-b40a-1d3b30fcb179, 93d74bcb-2e44-43b2-bb5d-40e16712c7f1]] is reporting status [Completing] for [Build [<project>/73/build/1/build/5669]]
INFO   | jvm 1    | 2020/03/23 11:42:53 | 2020-03-23 11:42:53,131 INFO  [qtp415774130-35] BuildRepositoryRemoteImpl:96 - [Agent [gocd-agent-dind-02ae1fc0-c94a-49a7-9831-f9fa2efca25d, 100.64.0.175, dfa856e5-93de-49f2-b40a-1d3b30fcb179, 93d74bcb-2e44-43b2-bb5d-40e16712c7f1]] is reporting status and result [Completed, Failed] for [Build [<project>/73/build/1/build/5669]]
INFO   | jvm 1    | 2020/03/23 11:42:53 | 2020-03-23 11:42:53,138 INFO  [qtp415774130-35] Stage:234 - Stage is being completed by transition id: 32408
```


And, the mos interesting one, the logfile of docker-registry artifact plugin:
```
2020-03-22 17:26:54,755 INFO  [Thread-78] DockerRegistryArtifactPlugin:72 - Loading plugin Artifact plugin for docker[null].
2020-03-22 17:26:55,672 ERROR [Thread-78] DockerRegistryArtifactPlugin:127 - Error while executing request go.plugin-settings.get-configuration
java.lang.NullPointerException: null
	at cd.go.artifact.docker.registry.DockerRegistryArtifactPlugin.handle(DockerRegistryArtifactPlugin.java:55)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:208)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:56)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.lambda$findSettingsAndViewOfAllExtensionsIn$2(PluginSettingsMetadataLoader.java:84)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.findSettingsAndViewOfAllExtensionsIn(PluginSettingsMetadataLoader.java:89)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:59)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:49)
	at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$0(PluginLoader.java:113)
	at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
	at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
	at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$1(PluginLoader.java:113)
	at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
	at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
	at com.thoughtworks.go.plugin.infra.PluginLoader.doPostBundleInstallActivities(PluginLoader.java:112)
	at com.thoughtworks.go.plugin.infra.PluginLoader.loadPlugin(PluginLoader.java:70)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:180)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:123)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:72)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:237)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:258)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:237)
	at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.lambda$notify$0(PluginChangeNotifier.java:33)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.notify(PluginChangeNotifier.java:30)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:204)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:192)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:177)
```

**Comment by JakkoJokiranta** [comment]
Got the solution. Problem was agents were deployed with imagePullPolicy IfNotPresent. That caused some agents to run with older gocd dind version than running one (20.1.0 against 20.2.0)
