### ISSUE TITLE
Am I getting this bug because I've missed something from the artifact configuration?

### ISSUE THREAD

**Issue by vernonr3** [gocd/docker-registry-artifact-plugin#922]
HI,
I'm getting an error trying to push an artifact to a private docker repository.
The repository is live and working. The build of the artifact plugin passed all tests..
The errors I get on the console are
```
[cd.go.artifact.docker.registry] Pushing docker image `registry.peregrinereporting.com:5000/dev:0.96-phfilebrowser:0.96` to docker registry `https://registry.peregrinereporting.com:5000`.
[cd.go.artifact.docker.registry] Failed to publish Artifact[id=phfilebrowser, storeId=peregrinereporting, artifactPlanConfig={"Image":"registry.peregrinereporting.com:5000/dev:0.96-phfilebrowser","Tag":"0.96"}]: com.spotify.docker.client.exceptions.DockerException: java.lang.NullPointerException: Cannot invoke "com.fasterxml.jackson.core.JsonParser.streamReadConstraints()" because "p" is null
```
Thanks

**Comment by chadlwilson** [comment]
Probably. The error message is terrible and needs improvement, but you need to share the full stack trace and logs from the server or plugin log itself to know what the problem is.

Also share GoCD and plugin version, please.

**Comment by vernonr3** [comment]
Thanks Chad,

GoCD version is 23.1.0-16079
Java version is 17.0.6
Plugin version is 1.3.1-431

Made some progress in tracking this down...
The plugin log shows the following 
```
2023-05-05 14:36:14,088 INFO  [Thread-79] DockerRegistryArtifactPlugin:72 - Loading plugin Artifact plugin for docker[null].
2023-05-05 14:36:15,537 ERROR [Thread-79] DockerRegistryArtifactPlugin:127 - Error while executing request go.plugin-settings.get-configuration
java.lang.NullPointerException: Cannot invoke "cd.go.artifact.docker.registry.Request.ordinal()" because the return value of "cd.go.artifact.docker.registry.Request.fromString(String)" is null
	at cd.go.artifact.docker.registry.DockerRegistryArtifactPlugin.handle(DockerRegistryArtifactPlugin.java:55)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.lambda$submitTo$0(DefaultPluginManager.java:134)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.executeActionOnTheService(FelixGoPluginOSGiFramework.java:205)
	at com.thoughtworks.go.plugin.infra.FelixGoPluginOSGiFramework.doOn(FelixGoPluginOSGiFramework.java:164)
	at com.thoughtworks.go.plugin.infra.DefaultPluginManager.submitTo(DefaultPluginManager.java:131)
	at com.thoughtworks.go.plugin.access.PluginRequestHelper.submitRequest(PluginRequestHelper.java:49)
	at com.thoughtworks.go.plugin.access.common.AbstractExtension.getPluginSettingsConfiguration(AbstractExtension.java:56)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.lambda$findSettingsAndViewOfAllExtensionsIn$2(PluginSettingsMetadataLoader.java:84)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(Unknown Source)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(Unknown Source)
	at java.base/java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.base/java.util.stream.ReferencePipeline.collect(Unknown Source)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.findSettingsAndViewOfAllExtensionsIn(PluginSettingsMetadataLoader.java:89)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.fetchPluginSettingsMetaData(PluginSettingsMetadataLoader.java:59)
	at com.thoughtworks.go.plugin.access.common.settings.PluginSettingsMetadataLoader.pluginLoaded(PluginSettingsMetadataLoader.java:49)
	at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$0(PluginLoader.java:112)
	at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
	at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
	at com.thoughtworks.go.plugin.infra.PluginLoader.lambda$doPostBundleInstallActivities$1(PluginLoader.java:112)
	at org.apache.commons.collections4.IteratorUtils.forEach(IteratorUtils.java:1224)
	at org.apache.commons.collections4.IterableUtils.forEach(IterableUtils.java:585)
	at com.thoughtworks.go.plugin.infra.PluginLoader.doPostBundleInstallActivities(PluginLoader.java:112)
	at com.thoughtworks.go.plugin.infra.PluginLoader.loadPlugin(PluginLoader.java:70)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.refreshBundle(DefaultPluginJarChangeListener.java:180)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.addPlugin(DefaultPluginJarChangeListener.java:123)
	at com.thoughtworks.go.plugin.infra.listeners.DefaultPluginJarChangeListener.pluginJarAdded(DefaultPluginJarChangeListener.java:72)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.lambda$pluginJarAdded$0(DefaultPluginJarLocationMonitor.java:237)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.doOnAllPluginJarChangeListener(DefaultPluginJarLocationMonitor.java:258)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread$DoOnAllListeners.pluginJarAdded(DefaultPluginJarLocationMonitor.java:237)
	at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.lambda$notify$0(PluginChangeNotifier.java:33)
	at java.base/java.lang.Iterable.forEach(Unknown Source)
	at com.thoughtworks.go.plugin.infra.monitor.PluginChangeNotifier.notify(PluginChangeNotifier.java:30)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.loadAndNotifyPluginsFrom(DefaultPluginJarLocationMonitor.java:204)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.oneShot(DefaultPluginJarLocationMonitor.java:192)
	at com.thoughtworks.go.plugin.infra.monitor.DefaultPluginJarLocationMonitor$PluginLocationMonitorThread.run(DefaultPluginJarLocationMonitor.java:177)
```
Tracking this down - it's a bit odd.. 
Seems as though the server is sending a REQUEST_PLUGIN_SETTINGS_CONFIGURATION as the list in PluginSettingsConstants.java in package com.thoughtworks.go.plugin.access.common.settings
but the artifact plugin expects to receive from a different list as per Request.java in package cd.go.artifact.docker.registry.
Almost as though the spec for plugins between the server and artifact plugin don't match..?? The list in Request.java doesn't seem to be anywhere in the goCD source code?
```
REQUEST_GET_PLUGIN_ICON("cd.go.artifact.get-icon"),
    REQUEST_GET_PLUGIN_CAPABILITIES("cd.go.artifact.get-capabilities"),

    REQUEST_STORE_CONFIG_METADATA("cd.go.artifact.store.get-metadata"),
    REQUEST_STORE_CONFIG_VIEW("cd.go.artifact.store.get-view"),
    REQUEST_STORE_CONFIG_VALIDATE("cd.go.artifact.store.validate"),

    REQUEST_PUBLISH_ARTIFACT_METADATA("cd.go.artifact.publish.get-metadata"),
    REQUEST_PUBLISH_ARTIFACT_VIEW("cd.go.artifact.publish.get-view"),
    REQUEST_PUBLISH_ARTIFACT_VALIDATE("cd.go.artifact.publish.validate"),

    REQUEST_FETCH_ARTIFACT_METADATA("cd.go.artifact.fetch.get-metadata"),
    REQUEST_FETCH_ARTIFACT_VIEW("cd.go.artifact.fetch.get-view"),
    REQUEST_FETCH_ARTIFACT_VALIDATE("cd.go.artifact.fetch.validate"),

    REQUEST_PUBLISH_ARTIFACT("cd.go.artifact.publish-artifact"),
    REQUEST_FETCH_ARTIFACT("cd.go.artifact.fetch-artifact");
```
I'm puzzled?

**Comment by chadlwilson** [comment]
That error is a red herring in this context as the GoCD server handles errors from plugins that don't support custom plugin settings. The server log will show it as a warning.

We want to see the full error/stack trace when you try to publish an artifact as in your original message.

Thinking a bit more clearly the artifact publish happens on the **agent**, so I guess the stack trace corresponding to `Cannot invoke "com.fasterxml.jackson.core.JsonParser.streamReadConstraints()" because "p" is null` would probably in one of the agent logs, or the plugin logs that sit on the agent that the job ran on (rather than on the server).

**Comment by vernonr3** [comment]
Sorry, messages crossed...

**Comment by vernonr3** [comment]
I'll try it. Is it better if I download the precompiled jar from github or clone and compile locally as before..?

**Comment by vernonr3** [comment]
I followed the instructions in the readme. The gradle script worked a treat.
OK I'll download the prebuilt version... Don't think there was an issue with the build - all the tests were fine... but let's see..

**Comment by chadlwilson** [comment]
OK, I guess there is a problem with one of the dependency upgrades that was obscuring the actual issue.

But no, you cant include the tag in the image name as the image:tag are separate concepts in Docker. Not sure what you mean about making it easier to manage in the registry though.

Anyway, once you workaround this and get things working, would you mind re-validating with [v1.3.1-433-exp](https://github.com/gocd/docker-registry-artifact-plugin/releases/tag/v1.3.1-433-exp) ? if that version also works OK, I'll release it properly to fix the main issue here. In this release I've rolled back the upgrade likely causing the issue.

**Comment by vernonr3** [comment]
Yes - your v1.3.1-433 works fine... 
I understand what you mean about image:tag being separate concepts in docker - As I understand it they are until one comes to the command line interface for building an image where -t for tag sets both the image name and tag. :-)
Thanks for the help... an essential part of making goCD viable...

**Comment by chadlwilson** [comment]
After looking a bit further I think the problem you had was actually only due to building your own jar off latest master (which had an unreleased jackson upgrade that seems to be at the root of this)

https://github.com/FasterXML/jackson-databind/issues/3913

I misread your plugin version and didn't realize that was an unreleased version you had built yourself. Anyway, will release a better fix soon.
